name: Tourism ML Pipeline

on:
  push:
    branches:
      - main

jobs:

  # ------------------------------
  # Job Template for Running Scripts
  # ------------------------------
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script-job: [register-dataset, data-prep, model-training, deploy-hosting]
    steps:
      - uses: actions/checkout@v3

      # Debug repo structure
      - name: List repository files
        run: ls -R

      # Install dependencies
      - name: Install Dependencies
        run: |
          REQ=$(find . -name "requirements.txt" | head -n 1)
          if [ -z "$REQ" ]; then
            echo "❌ requirements.txt not found"
            exit 1
          fi
          echo "Installing from $REQ"
          pip install -r $REQ

      # Map job name to script path
      - name: Run Python Script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          case "${{ matrix.script-job }}" in
            register-dataset)
              SCRIPT=$(find . -path "*/tourism_project/model_building/data_register.py" | head -n 1)
              ;;
            data-prep)
              SCRIPT=$(find . -path "*/tourism_project/model_building/prep.py" | head -n 1)
              ;;
            model-training)
              SCRIPT=$(find . -path "*/tourism_project/model_building/train.py" | head -n 1)
              # Start MLflow in background
              nohup mlflow ui --host 0.0.0.0 --port 5000 >/dev/null 2>&1 &
              sleep 5
              ;;
            deploy-hosting)
              SCRIPT=$(find . -path "*/tourism_project/deployment/hosting.py" | head -n 1)
              ;;
            *)
              echo "Unknown job"
              exit 1
              ;;
          esac

          if [ -z "$SCRIPT" ]; then
            echo "❌ Script not found for job ${{ matrix.script-job }}"
            exit 1
          fi
          echo "Running $SCRIPT"
          python $SCRIPT
